[package]
name = "dcrs"
version = "0.0.2"
edition = "2021"
authors = ["github.com/grhx"]

description = "Discord API Library"
readme = "README.md"
license = "MIT"
keywords = ["discord", "bot", "api"]

repository = "https://github.com/grhx/dcrs"

[dependencies]
